scalar DateTime
scalar NumberId

type Query {
  product(id: ID!): Product
  products: [Product]
}

type Mutation {
  storeProduct(input: ProductInput): ApiProductResponse
  destroyProduct(id: ID!): ApiProductResponse
  updateProduct(id: ID!, input: ProductInput): ApiProductResponse
}

type Product {
  id: NumberId
  name: String
  price: NumberId
  image: String
  created_at: DateTime
  updated_at: DateTime
}

type ApiProductResponse {
  success: Boolean
  message: String
  data: Product
}

input ProductInput {
  name: String!
  price: Float!
  image: String!
}
